services:
  - type: web
    name: gia-su-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
